# Generated by Django 4.1.3 on 2022-12-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonecatalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_make', models.CharField(help_text='Enter a phone make (e.g. Samsung)', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='launch_date',
            field=models.DateTimeField(null=True, verbose_name='date launched'),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='sale_currency',
            field=models.CharField(choices=[('Kshs', 'Kenya Shillings'), ('Dollar', 'US Dollars'), ('Euro', 'Euros'), ('Pound', 'Pounds')], default='Kshs', max_length=10),
        ),
        migrations.AddField(
            model_name='phone',
            name='sku',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='phone',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='phonecatalog.phonemake'),
        ),
    ]
