# Generated by Django 4.1.3 on 2022-12-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonecatalog', '0002_phonemake_phone_launch_date_phone_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='operating_system',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
